# Generated by Django 4.1.2 on 2022-10-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_nullblankdemo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nullblankdemo',
            name='blank',
        ),
        migrations.RemoveField(
            model_name='nullblankdemo',
            name='null',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_full_time',
            field=models.BooleanField(null=True),
        ),
    ]
