# Generated by Django 4.1.2 on 2022-10-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_nullblankdemo_blank_remove_nullblankdemo_null_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='review',
            new_name='level',
        ),
    ]
