# Generated by Django 4.1.2 on 2022-10-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_review_employee_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.TextField(choices=[('jr', 'Junior'), ('in', 'Intern'), ('reg', 'Regular')], verbose_name='Seniority level'),
        ),
    ]
