# Generated by Django 4.1.2 on 2022-10-08 20:55

from django.db import migrations, models
import models_django.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(validators=[models_django.web.validators.validate_before_today]),
        ),
    ]
