# Generated by Django 4.1.2 on 2022-10-30 08:50

import car_collection_app.car_collection.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_collection', '0004_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(validators=[car_collection_app.car_collection.validators.validate_years]),
        ),
    ]
