# Generated by Django 4.1.2 on 2022-10-30 10:35

import car_collection_app.car_collection.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_collection', '0007_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=10, validators=[car_collection_app.car_collection.validators.validate_min_len_username], verbose_name='Username'),
        ),
    ]
