# Generated by Django 4.1.2 on 2022-10-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_demos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='pets',
            field=models.ManyToManyField(to='forms_demos.pet'),
        ),
    ]
